//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImdbServiceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies
    {
        public string tconst { get; set; }
        public string titleType { get; set; }
        public string primaryTitle { get; set; }
        public string originalTitle { get; set; }
        public Nullable<bool> isAdult { get; set; }
        public Nullable<short> startYear { get; set; }
        public Nullable<short> endYear { get; set; }
        public Nullable<int> runtimeMinutes { get; set; }
        public string genres { get; set; }
    }
}
